### ISSUE TITLE
pecanpico10

### ISSUE THREAD

**Issue by SwiftFlying** [DL7AD/pecanpico10#5]
Hi,
PECANPICO10, will there be any image transmission error?

**Comment by DL7AD** [comment]
Hi,

If you try to transmit an image without a camera attached to the Pecan itself, it will transmit an error picture instead.

Sven

**Comment by SwiftFlying** [comment]
Hi,
https://github.com/TomasTT7/LoRa_SSDV
I'm testing LoRa_SSDV, Images transmitted are prone to errors. The author says there's something wrong with the camera power.I'm trying to solve this problem.And plans to build a relay device.

Tom

**Comment by DL7AD** [comment]
Hi,

I have to admit that the SSDV algorithm is slightly modified from the original one because a APRS packet can't handle such long packets and overall also no binary data. The SyncByte, FEC and CRC is also not transmitted in the APRS packet because there is no need for it inside the APRS packet.

I shorten the SSDV packet by adding a new type
`#define SSDV_TYPE_PADDING (0x48)`

That option prevents the SSDV algorithm by putting so many bytes the packet. The additional data is simply put in the next packet. If you try to decode it with the very original SSDV code, you get an offset of the data.

While APRS can't handle binary data, we encode everything in base91 on top of it.

Sven
